name: Syncing two repo
on: push

env:
  SOURCE_REPO: "git@github.com:UwUClub/Zappy.git" #Insert source url of the git source repo
  DEST_REPO: "git@github.com:EpitechPromo2026/B-YEP-400-TLS-4-1-zappy-maxence.labourel.git" #Insert Destination url of the git dest repo

jobs:
  git-sync:
    needs: check_repo
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ env.SOURCE_REPO }}
          source_branch: "main"
          destination_repo: ${{ env.DEST_REPO }}
          destination_branch: "main"
          ssh_private_key: ${{ secrets.SSH_KEY }}
